import "@/styles/globals.css";
import Head from "next/head";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import localFont from "next/font/local";

const Catamaran = localFont({
  src: [
    {path: './fonts/Catamaran-Thin.ttf'}
    // {
    //   path: "./fonts/Catamaran-Thin.ttf",
    //   style: "thin",
    // },
    // {
    //   path: "./fonts/Catamaran-SemiBold.ttf",
    //   style: "semibold",
    // },
    // {
    //   path: "./fonts/Catamaran-Regular.ttf",
    //   style: "regular",
    // },
    // {
    //   path: "./fonts/Catamaran-Medium.ttf",
    //   style: "medium",
    // },
    // {
    //   path: "./fonts/Catamaran-Light.ttf",
    //   style: "light",
    // },
    // {
    //   path: "./fonts/Catamaran-ExtraLight.ttf",
    //   style: "extralight",
    // },
    // {
    //   path: "./fonts/Catamaran-Bold.ttf",
    //   style: "bold",
    // },
    // {
    //   path: "./fonts/Catamaran-ExtraBold.ttf",
    //   style: "extrabold",
    // },
    // {
    //   path: "./fonts/Catamaran-Black.ttf",
    //   style: "black",
    // },


    //   {
    //     path: './fonts/Helvetica.ttf',
    //     weight: '400',
    //     // style: 'normal',
    //   },
    //   {
    //     path: './fonts/Helvetica.ttf',
    //     weight: '500',
    //     // style: 'semibold',
    //   },

    //   {
    //     path: './fonts/Helvetica-Bold.ttf',
    //     weight: '600',
    //     // style: 'bold',
    //   },

    //   {
    //     path: './fonts/HelveticaNeueBold.ttf',
    //     weight: '700',
    //     style: 'bold',
    //   },
  ],
  // variable: "--font-Helvetica",
  variable: "--font-Catamaran",
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Allbirds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* <main className={Catamaran.className}> */}
        <Header />
        <Component {...pageProps} />
        <Footer />
      {/* </main> */}
    </>
  );
}
