export  const newArrivalsList = [
  { id: 1, img: "/category/shoes/shoe1.png", title: "Women's Tree Tlyers 2", subTitle: "Blizzard", link: "/" },
  { id: 2, img: "/category/shoes/shoe2.png", title: "Men's Tree Tlyers 2", subTitle: "Natural Black", link: "/" },
  { id: 3, img: "/category/shoes/shoe3.png", title: "Women's Riser", subTitle: "Allbirds x Olivia Rubin", link: "/" },
  { id: 4, img: "/category/shoes/shoe4.png", title: "Men's Tree Dasher Relay", subTitle: "Hazy Indigo", link: "/" },
  { id: 5, img: "/category/shoes/shoe5.png", title: "Women's Tree Runner", subTitle: "Arid Umber", link: "/" },
  { id: 7, img: "/category/fav1.jpg", title: "", subTitle: "", link: "/" },
  { id: 8, img: "", title: "", subTitle: "", link: "/" },
  { id: 9, img: "", title: "", subTitle: "", link: "/" },
  { id: 10, img: "", title: "", subTitle: "", link: "/" },
  { id: 11, img: "", title: "", subTitle: "", link: "/" },
  { id: 12, img: "", title: "", subTitle: "", link: "/" },
  { id: 13, img: "", title: "", subTitle: "", link: "/" },
  { id: 14, img: "", title: "", subTitle: "", link: "/" },
  { id: 15, img: "", title: "", subTitle: "", link: "/" },
  { id: 16, img: "", title: "", subTitle: "", link: "/" },
];
