export const saleList = [
  {
    id: 1,
    title: "Men's Trail Runners SWT",
    image: [
      {
        id: 1,
        img: "/category/shoes/sShow1.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 2,
        img: "/category/shoes/sShow2.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 3,
        img: "/category/shoes/sShow3.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 4,
        img: "/category/shoes/sShow4.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 5,
        img: "/category/shoes/sShow5.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 6,
        img: "/category/shoes/sShow6.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 7,
        img: "/category/shoes/sShow7.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 8,
        img: "/category/shoes/sShow8.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 9,
        img: "/category/shoes/sShow9.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
    ],
  },
  {
    id: 2,
    title: "2 Men's Trail Runners SWT",
    image: [
      {
        id: 1,
        img: "/category/shoes/sShow2.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 2,
        img: "/category/shoes/sShow2.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 3,
        img: "/category/shoes/sShow3.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 4,
        img: "/category/shoes/sShow4.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 5,
        img: "/category/shoes/sShow5.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 6,
        img: "/category/shoes/sShow6.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 7,
        img: "/category/shoes/sShow7.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 8,
        img: "/category/shoes/sShow8.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
      {
        id: 9,
        img: "/category/shoes/sShow9.jpg",
        subtitle: "Honey Rust (Forage Tan Sole)",
        mrp: "220",
        disMrp: "250",
      },
    ],
  },
];
